// Code in this file has been generated by Equinox's ImageCodeGenerator

using System.Collections.Generic;
using EquinoxsModUtils;
using UnityEngine;

namespace ConsoleCommands 
{
    internal static class Images {
        internal static bool initialised = false;

        internal static void InitialiseStyles(){
            // ToDo: Copy next line to OnGUI() 
            // if(!Images.initialised) Images.InitialiseStyles();
            initialised = true;
            foreach(ModImage modImage in modImages){
                modImage.InitialiseStyle();
            }
        }
        
        internal static ModImage center = new ModImage("Center.png", 492, 40);
        internal static ModImage left = new ModImage("Left.png", 10, 40);
        internal static ModImage right = new ModImage("Right.png", 10, 40);

        internal static class HelpBox {
            
            internal static ModImage bottom = new ModImage("HelpBox.Bottom.png", 80, 11);
            internal static ModImage bottomLeft = new ModImage("HelpBox.BottomLeft.png", 11, 11);
            internal static ModImage bottomRight = new ModImage("HelpBox.BottomRight.png", 11, 11);
            internal static ModImage center = new ModImage("HelpBox.Center.png", 80, 20);
            internal static ModImage horizontal = new ModImage("HelpBox.Horizontal.png", 80, 42);
            internal static ModImage left = new ModImage("HelpBox.Left.png", 11, 20);
            internal static ModImage orangePixel = new ModImage("HelpBox.OrangePixel.png", 1, 1);
            internal static ModImage right = new ModImage("HelpBox.Right.png", 11, 20);
            internal static ModImage top = new ModImage("HelpBox.Top.png", 80, 11);
            internal static ModImage topLeft = new ModImage("HelpBox.TopLeft.png", 11, 11);
            internal static ModImage topRight = new ModImage("HelpBox.TopRight.png", 11, 11);
            internal static ModImage vertical = new ModImage("HelpBox.Vertical.png", 102, 20);
        }

        private static List<ModImage> modImages = new List<ModImage>() {
            center,
            left,
            right,
            HelpBox.bottom,
            HelpBox.bottomLeft,
            HelpBox.bottomRight,
            HelpBox.center,
            HelpBox.horizontal,
            HelpBox.left,
            HelpBox.orangePixel,
            HelpBox.right,
            HelpBox.top,
            HelpBox.topLeft,
            HelpBox.topRight,
            HelpBox.vertical
        };
    }

    internal class ModImage{
        internal float width;
        internal float height;
    
        internal Texture2D texture2d;
        internal Sprite sprite;
        internal Rect rect;
        internal GUIStyle style;

        internal void InitialiseStyle(){
            style = new GUIStyle() { normal = { background = texture2d } };
        }

        internal void Draw(float xPos, float yPos) {
            rect.x = xPos;
            rect.y = yPos;
            UnityEngine.GUI.Box(rect, "", style);
        }

        internal void Draw(float xPos, float yPos, float _width, float _height){
            rect = new Rect(xPos, yPos, _width, _height);
            UnityEngine.GUI.Box(rect, "", style);
        }

        internal bool DrawAsButton(float xPos, float yPos) {
            rect.x = xPos;
            rect.y = yPos;
            return UnityEngine.GUI.Button(rect, "", style);
        }

        internal bool DrawAsButton(float xPos, float yPos, float _width, float _height) {
            rect = new Rect(xPos, yPos, _width, _height);
            return UnityEngine.GUI.Button(rect, "", style);
        }
  
        internal ModImage(string path, float _width, float _height){
            width = _width;
            height = _height;
            rect = new Rect(0, 0, width, height);
  
            string embeddedPath = $"ConsoleCommands.Images.{path}";
            texture2d = ModUtils.LoadTexture2DFromFile(embeddedPath);
            sprite = ModUtils.LoadSpriteFromFile(embeddedPath);
        }
    }
}